package com.jasonernst.icmp_common.v6

import com.jasonernst.icmp_common.ICMPType

// https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml
enum class ICMPv6Type(override val value: UByte) : ICMPType {
    RESERVED(0U),
    DESTINATION_UNREACHABLE(1U),
    PACKET_TOO_BIG(2U),
    TIME_EXCEEDED(3U),
    PARAMETER_PROBLEM(4U),
    ECHO_REQUEST_V6(128U),
    ECHO_REPLY_V6(129U),
    MULTICAST_LISTENER_QUERY(130U),
    MULTICAST_LISTENER_REPORT(131U),
    MULTICAST_LISTENER_DONE(132U),
    ROUTER_SOLICITATION_V6(133U),
    ROUTER_ADVERTISEMENT_V6(134U),
    NEIGHBOR_SOLICITATION(135U),
    REDIRECT_V6(137U),
    ROUTER_RENUMBERING(138U),
    INFORMATION_REQUEST(139U),
    INFORMATION_REPLY(140U),
    INVERSE_NEIGHBOR_DISCOVERY_SOLICITATION(141U),
    INVERSE_NEIGHBOR_DISCOVERY_ADVERTISEMENT(142U),
    MULTICAST_LISTENER_DISCOVERY_V2(143U),
    HOME_AGENT_ADDRESS_DISCOVERY_REQUEST(144U),
    HOME_AGENT_ADDRESS_DISCOVERY_REPLY(145U),
    MOBILE_PREFIX_SOLICITATION(146U),
    MOBILE_PREFIX_ADVERTISEMENT(147U),
    CERTIFICATION_PATH_SOLICITATION(148U),
    CERTIFICATION_PATH_ADVERTISEMENT(149U),
    EXPERIMENTAL_MOBILITY_PROTOCOLS(150U),
    MULTICAST_ROUTER_ADVERTISEMENT(151U),
    MULTICAST_ROUTER_SOLICITATION(152U),
    MULTICAST_ROUTER_TERMINATION(153U),
    FMIPV6_MESSAGES(154U),
    RPL_CONTROL_MESSAGE(155U),
    ILNPV6_LOCATOR_UPDATE_MESSAGE(156U),
    DUPLICATE_ADDRESS_REQUEST(157U),
    DUPLICATE_ADDRESS_CONFIRMATION(158U),
    MPL_CONTROL_MESSAGE(159U),
    EXTENDED_ECHO_REQUEST(160U),
    EXTENDED_ECHO_REPLY(161U),
    ;

    companion object {
        fun fromValue(value: UByte) = entries.first { it.value == value }
    }
}